name: CI

on:
  create:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    inputs:
      ReleaseType:
        description: 'Release or Debug'
        required: true
        default: 'Release'

jobs:
  Build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: macos-latest
          - os: ubuntu-latest
          - os: windows-latest
            architecture: x64
          - os: windows-latest
            architecture: x86
          - os: windows-latest
            architecture: ARM64

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive

      - name: Setup .NET
        if: matrix.os == 'windows-latest'
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      - name: Enable WndProcHandler
        if: matrix.os == 'windows-latest'
        run: |
          # Modify imgui_impl_win32.h to enable WndProcHandler
          $headerPath = "cimgui/imgui/backends/imgui_impl_win32.h"
          $content = Get-Content $headerPath -Raw
          $content = $content -replace '#if 0\s*extern IMGUI_IMPL_API LRESULT ImGui_ImplWin32_WndProcHandler.*?#endif', 'extern IMGUI_IMPL_API LRESULT ImGui_ImplWin32_WndProcHandler(HWND hWnd, UINT msg, WPARAM wParam, LPARAM lParam);'
          $content | Set-Content $headerPath
          
          # Add implementation file to build
          $cmakePath = "cimgui/CMakeLists.txt"
          $cmakeContent = Get-Content $cmakePath -Raw
          if (-not ($cmakeContent -match "imgui_impl_win32.cpp")) {
            $cmakeContent = $cmakeContent -replace 'imgui_impl_dx11.cpp', 'imgui_impl_dx11.cpp imgui/backends/imgui_impl_win32.cpp'
            $cmakeContent | Set-Content $cmakePath
          }
        shell: pwsh

      - name: Build source package
        if: matrix.os == 'windows-latest' && matrix.architecture == 'x64'
        run: dotnet pack -c Release ImGui.NET.SourceBuild.csproj
        shell: bash

      - name: Upload source package
        uses: actions/upload-artifact@v4
        if: matrix.os == 'windows-latest' && matrix.architecture == 'x64'
        with:
          name: win-x64-source
          path: bin\Packages\Release\*.nupkg

      - name: Build ${{ github.event.inputs.ReleaseType || 'Release' }}
        run: |
          if [ "$RUNNER_OS" == "Windows" ]; then
            ./ci-build.cmd ${{ github.event.inputs.ReleaseType || 'Release' }} ${{ matrix.architecture }}
          else
            ./ci-build.sh ${{ github.event.inputs.ReleaseType || 'Release' }}
          fi
        shell: bash

      - name: Verify WndProcHandler Export
        if: matrix.os == 'windows-latest'
        run: |
          dumpbin /exports "cimgui\build\${{ matrix.architecture }}\${{ github.event.inputs.ReleaseType || 'Release' }}\cimgui.dll" | findstr "WndProcHandler"
        shell: cmd

      - name: Upload win-${{ matrix.architecture }} ${{ github.event.inputs.ReleaseType || 'Release' }}
        uses: actions/upload-artifact@v4
        if: matrix.os == 'windows-latest'
        with:
          name: win-${{ matrix.architecture }}
          path: cimgui\build\${{ matrix.architecture }}\${{ github.event.inputs.ReleaseType || 'Release' }}\*

      - name: Upload ${{ matrix.os }} ${{ github.event.inputs.ReleaseType || 'Release' }}
        uses: actions/upload-artifact@v4
        if: matrix.os == 'ubuntu-latest' || matrix.os == 'macos-latest'
        with:
          name: ${{ matrix.os }}-x64
          path: cimgui/build/${{ github.event.inputs.ReleaseType || 'Release' }}/*

      - name: Upload Json Files
        uses: actions/upload-artifact@v4
        if: matrix.os == 'windows-latest' && matrix.architecture == 'x64'
        with:
          name: JsonFiles
          path: cimgui\generator\output\*.json

      - name: Publish untagged source package to MyGet
        if: matrix.os == 'windows-latest' && github.ref == 'refs/heads/master' && matrix.architecture == 'x64'
        run: dotnet nuget push bin\Packages\Release\*.nupkg -s https://www.myget.org/F/mellinoe/api/v3/index.json --api-key ${{secrets.MYGET_KEY}}
        continue-on-error: true

      - name: Publish tagged source package release to nuget.org
        if: matrix.os == 'windows-latest' && startsWith(github.ref, 'refs/tags/') && matrix.architecture == 'x64'
        run: dotnet nuget push bin\Packages\Release\*.nupkg -s https://api.nuget.org/v3/index.json --api-key ${{secrets.NUGET_KEY}}
        continue-on-error: true

  CreateReleaseOnTagCreate:
    runs-on: ubuntu-latest
    needs: [Build]
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Download Artifacts
        uses: actions/download-artifact@v4

      - name: Rename win-x64 and win-x86 artifacts
        run: |
          mv win-x64/cimgui.dll win-x64/cimgui.win-x64.dll
          mv win-x86/cimgui.dll win-x86/cimgui.win-x86.dll
          mv win-ARM64/cimgui.dll win-ARM64/cimgui.win-arm64.dll

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            win-x64/cimgui.win-x64.dll
            win-x86/cimgui.win-x86.dll
            win-ARM64/cimgui.win-arm64.dll
            JsonFiles/*
            ubuntu-latest-x64/cimgui.so
            macos-latest-x64/cimgui.dylib